services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: smartmatchai_pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: smartmatch
    # 5433 vs 5432 for host in case there is a local postgres instance running
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: smartmatchai_app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      # Override the connection string for container-to-container communication
      # This is internal communication so the port stays as 5432 as its available on the container
      - PGVECTOR_CONNECTION=postgresql+psycopg://postgres:test@postgres:5432/smartmatch

volumes:
  pgdata:
