services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: smartmatchai_pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: smartmatch
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: smartmatchai_app
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - .:/app
  #   environment:
  #     - PGVECTOR_CONNECTION=postgresql+psycopg://postgres:test@smartmatchai_pgvector:5432/smartmatch      

volumes:
  pgdata:
